config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users, controllers: { invitations: 'users/invitations' }

  namespace :admin do
    resources :plans
    resources :features
    resources :usage
    resources :payments
  end   
  
  namespace :buyer do
    resources :plans, only: %i[index show]
    resources :subscriptions
    resources :consume_features do
      member do
        patch :increment_consumed_unit
      end
    end
    resources :payments do
      member do
        patch :payment_status
      end
    end
  end
  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'signup', to: 'registrations#create'
        post 'signin', to: 'sessions#create'
        delete 'signout', to: 'sessions#destroy'
      end
      resources :plans
      post 'my_plans', to: 'plans#my_plans'
      post 'subscribe', to: 'subscriptions#create'
      delete 'unsubscribe', to: 'subscriptions#destroy'
    end
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :plan
  has_many :consume_features, dependent: :destroy
end

app/controllers/api/v1/subscriptions_controller.rb
class Api::V1::SubscriptionsController < Api::ApiController

  def create
    @subscription = current_user.subscriptions.new(plan_id: params[:plan_id])
     if @subscription.save
       json_status(:ok, 'You subscribed this plan')
      else
        json_status(:bad_request, 'Invalid plan_id or authorization token')
      end

  end

  def destroy
    @subscription = current_user.subscriptions.find(params[:id])
    if @subscription.blank?
      json_status(:bad_request, 'You do not have any subscription')
    else
      @subscription.destroy
      json_status(:ok, 'You Unsubscribed this plan')
    end
  end
end

app/controllers/buyer/consume_features_controller.rb
class Buyer::ConsumeFeaturesController < ApplicationController
  def increment_consumed_unit
    @subscription = current_user.subscriptions.find_by(plan_id: params[:plan_id])
    @consume_feature = ConsumeFeature.find_or_create_by(consume_feature_params)
    @consume_feature.increment!(:consume_units)
    respond_to do |format|
      format.js
    end
  end

  private

  def consume_feature_params
    params.require(:consume_feature).permit(:subscription_id, :feature_id, :consume_units)
  end
end

app/controllers/buyer/features_controller.rb
class Buyer::FeaturesController < ApplicationController
end

app/controllers/buyer/payments_controller.rb
class Buyer::PaymentsController < ApplicationController
  def index
    @payments = current_user.payments
  end

  def payment_status
    @payment = current_user.payments.find(params[:id])
    @payment.update(payment: true )
    redirect_to buyer_payments_path, notice: 'Bill amount has been deducted from your account'
  end
end

app/controllers/buyer/plans_controller.rb
class Buyer::PlansController < ApplicationController
  def index
    @plans = Plan.all
  end

  def show
    @plan = Plan.find(params[:id])
  end
end

app/controllers/buyer/subscriptions_controller.rb
class Buyer::SubscriptionsController < ApplicationController
  before_action :set_subscription, only: :destroy

  def index
    @subscriptions = current_user.subscriptions.includes(:consume_features, plan: [feature_plans: [:feature]])
    @bill = current_user.payments
  end

  def create
    @subscription = Subscription.create!(subscription_params)
    redirect_to buyer_subscriptions_path, notice: 'Plan subscribed successfully!'
  end

  def destroy
    @subscription.destroy
    redirect_to buyer_plans_path, notice: 'Plan successfully unsubscribed.'
  end

  private

  def set_subscription
    @subscription = current_user.subscriptions.find(params[:id])
  end

  def subscription_params
    params.require(:subscription).permit(:subscription_name, :price, :user_id, :plan_id)
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
  def get_consume_feature(consume_features, feature_id)
    consume_features.find { |consume_feature| consume_feature.feature_id == feature_id }
  end

  def due_payment(user)
    user.payments.where(payment: false).pluck(:total_bill).sum
  end
end

app/views/buyer/subscriptions/_new.html.erb
<%= link_to 'Subscribe', buyer_subscriptions_path(subscription: {subscription_name: plan.plan_name, price: plan.monthly_fee, user_id: current_user.id, plan_id: plan.id}), method: :create, class: 'btn btn-warning',data: { confirm: 'Are you sure? Plan price will be charged!'} %>

app/views/buyer/subscriptions/_subsucribe.html.erb
<%= link_to 'Subscribe', buyer_subscriptions_path(subscription: {subscription_name: plan.plan_name, price: plan.monthly_fee, user_id: current_user.id, plan_id: plan.id }), method: :create, class: 'btn btn-warning',data: { confirm: 'Are you sure? Plan price will be charged!'} %>

app/views/buyer/subscriptions/index.html.erb
<h1 class='text-center text-info my-4'> Your Subscriptions </h1>
<ul class='list-group'>
  <% @subscriptions.each do |subscription| %>
    <li class='list-group-item'>
      <strong class='text-primary'>Subscription Name: </strong>
      <%= subscription.subscription_name %>
    </li>
    <li class='list-group-item'>
      <strong class='text-primary'>Price: </strong> <%= subscription.price %>$
    </li>
    <li class='list-group-item'>
      <%= link_to 'Unsubscribe', buyer_subscription_path(subscription), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    </li>
    <% subscription.plan.features.each do |feature| %>
      <li class='list-group-item'>
        <strong class='text-primary'>Feature Name: </strong>
        <%= feature.feature_name %>
      </li>
      <li class='list-group-item'>
        <strong class='text-primary'>Unit Price: </strong> <%= feature.unit_price %>$
      </li>
      <li class='list-group-item'>
        <strong class='text-primary'>Max Unit Limit: </strong>
        <%= feature.max_unit_limit %>
      </li>
      <% consume_feature = get_consume_feature(subscription.consume_features, feature.id) %>
      <% if consume_feature %>
        <li class='list-group-item d-flex flex-row'>
          <strong class='text-primary '>Consumed Units: </strong>
          <div id='consume-<%= feature.id %>-<%= subscription.id %>' class ='ms-1'>
          <%= consume_feature.consume_units %></div>
        </li>
        <li class='list-group-item d-none message-<%=feature.id%>-<%= subscription.id %>'>
          <div class='alert alert-success' role='alert'>
            Unit consumed for this feature!
          </div>
        </li>
        <li class='list-group-item d-none error-<%=feature.id%>-<%= subscription.id %>'>
          <div class='alert alert-danger' role='alert'>
            Error! Couldn't consume this feature!
          </div>
        </li>
      <% else %>
        <li class='list-group-item'>
          <strong class='text-primary'>Consumed Units: </strong> 0
        </li>
      <% end %>
      <li class='list-group-item'>
        <%= link_to 'Consume Unit', increment_consumed_unit_buyer_consume_feature_path(feature.id, consume_feature: {feature_id: feature.id, subscription_id: subscription.id}), method: :patch, class: 'btn btn-success', remote: true %>
       </li>
    <% end %>
    <hr class='border border-success border-2 mb-4'>
  <% end %>
</ul>

<div class='mb-3 d-flex flex-row'>
  <% if @bill %>
    <h5 class='text-danger ms-4'> Due Bill is:
      <%= due_payment(current_user)%>$
      <button type='button' class='btn  btn-warning my-4 ms-3' data-bs-toggle='modal'
         data-bs-target='#invoice'>
        View Invoice
      </button>
      <%= render 'shared/invoice' %>
    </h5>
  <% end %>
  <div>
    <%= link_to 'Please Pay to enjoy Services',buyer_payments_path,
                                           class: 'btn btn-info mt-4 ms-4' %>
  </div>
</div>