config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users, controllers: { invitations: 'users/invitations' }

  namespace :admin do
    resources :plans
    resources :features
    resources :usage
    resources :payments
  end   
  
  namespace :buyer do
    resources :plans, only: %i[index show]
    resources :subscriptions
    resources :consume_features do
      member do
        patch :increment_consumed_unit
      end
    end
    resources :payments do
      member do
        patch :payment_status
      end
    end
  end
  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'signup', to: 'registrations#create'
        post 'signin', to: 'sessions#create'
        delete 'signout', to: 'sessions#destroy'
      end
      resources :plans
      post 'my_plans', to: 'plans#my_plans'
      post 'subscribe', to: 'subscriptions#create'
      delete 'unsubscribe', to: 'subscriptions#destroy'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/consume_feature.rb
class ConsumeFeature < ApplicationRecord
  belongs_to :subscription
  belongs_to :feature
end

app/models/feature.rb
class Feature < ApplicationRecord
  validates :feature_name, :code, :unit_price, :max_unit_limit, presence: true

  has_many :feature_plans, dependent: :destroy
  has_many :plans, through: :feature_plans
  has_many :consume_features
end

app/models/feature_plan.rb
class FeaturePlan < ApplicationRecord
  belongs_to :plan
  belongs_to :feature
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  belongs_to :plan, optional: true
end

app/models/plan.rb
class Plan < ApplicationRecord
  validates :plan_name, :monthly_fee, presence: true

  has_many :feature_plans, dependent: :destroy
  has_many :features, through: :feature_plans
  accepts_nested_attributes_for :feature_plans, reject_if: :all_blank, allow_destroy: true
  has_many :subscriptions
  has_many :users, through: :subscriptions
  has_many :payments
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :plan
  has_many :consume_features, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, validate_on_invite: true

  validates :avatar, attached: true,
                        content_type: %i[png jpg jpeg],
                        size: { less_than: 2.megabytes , message: 'must be less than 2MB in size' }

  ROLES = [:admin, :buyer]

  enum role: ROLES

  scope :user_subscriptions, -> { joins(:subscriptions).distinct }

  has_one_attached :avatar
  has_many :subscriptions
  has_many :payments
  has_many :plans, through: :subscriptions

  def generate_auth_token!
    begin
     self.auth_token = Devise.friendly_token
    end while self.class.exists?(auth_token: auth_token)
  end
end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < ApplicationController
  before_action :authorize_admin

  protected

  def authorize_admin
    return redirect_to buyer_plans_path unless current_user.admin?
  end
end

app/controllers/admin/features_controller.rb
class Admin::FeaturesController < Admin::AdminsController
  before_action :set_feature, only: %i[show edit update destroy]

  def index
    @features = Feature.all
  end

  def show; end

  def new
    @feature = Feature.new
  end

  def edit; end

  def create
    @feature = Feature.new(feature_params)

    if @feature.save
      redirect_to admin_features_path
    else   
      render 'new'
    end  
  end

  def update
    if @feature.update(feature_params)
      redirect_to admin_feature_path(@feature)
    else
      render 'edit'
    end
  end  

  def destroy
    @feature.destroy
    redirect_to admin_features_path
  end

  private

  def set_feature
    @feature = Feature.find(params[:id])
  end

  def feature_params
    params.require(:feature).permit(:feature_name, :code, :unit_price, :max_unit_limit)
  end
end

app/controllers/admin/payments_controller.rb
class Admin::PaymentsController < Admin::AdminsController
  def create
    total_amount = PaymentService.new(payment_params[:plan_id], payment_params[:user_id]).call
    if Payment.create(payment_params.merge(total_bill: total_amount))
     redirect_to admin_usage_path(payment_params[:user_id]), notice: 'Payment Generated!'
    else
      redirect_to admin_usage_path(payment_params[:user_id]), alert: 'Error! Payment can not be generated!'
    end
  end

  def show
    @buyer = User.buyer.find(params[:id])
    @payments = @buyer.payments
  end

  private

  def payment_params
    params.require(:payment).permit(:user_id, :plan_id, :total_bill)
  end
end

app/controllers/admin/plans_controller.rb
class Admin::PlansController < Admin::AdminsController
  before_action :set_plan, only: %i[show edit update destroy]
  
  def index
    @plans = Plan.all
  end 
  
  def new
    @plan = Plan.new
  end  

  def create
    @plan = Plan.create(plan_params)

    if @plan.save 
      redirect_to admin_plans_path
    else
      render 'new'
    end   
  end

  def edit; end

  def update
    if @plan.update(plan_params)
      redirect_to admin_plans_path
    else
      render 'edit'
    end
  end

  def destroy
    @plan.destroy
    redirect_to admin_plans_path
  end

  private

  def plan_params
    params.require(:plan).permit(:plan_name, :monthly_fee, feature_plans_attributes: [:id, :plan_id, :feature_id, :allocated_units, :_destroy])
  end

  def set_plan
    @plan = Plan.find(params[:id])
  end
end 

app/controllers/admin/usage_controller.rb
class Admin::UsageController < Admin::AdminsController
  def index
    @users = User.user_subscriptions
  end

  def show
    @buyer = User.buyer.find(params[:id])
    @subscriptions = @buyer.subscriptions.includes(:consume_features, plan: [feature_plans: [:feature]])
  end
end

app/controllers/api/api_controller.rb
class Api::ApiController < ActionController::Base
  include Response

  protect_from_forgery with: :null_session
  respond_to :json
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  before_action :ensure_token

  def current_user
    token = request.headers['authorization'].presence
    if token
      @current_user ||= User.find_by_auth_token(token)
    end
  end

  def authenticate_with_token!
    json_status(:unauthorized, 'Not authenticated') unless current_user.present?
  end

  def not_found
    json_status(:not_found, 'Could not find any data')
  end

   def ensure_token
    return if current_user
    json_status(:bad_request, 'Authorization Token not exists')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    return admin_plans_path if current_user.admin?
    return buyer_plans_path if current_user.buyer?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :role) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :role) }
    devise_parameter_sanitizer.permit(:invite, keys: [:name, :avatar, :role])
  end
end

app/controllers/buyer/features_controller.rb
class Buyer::FeaturesController < ApplicationController
end

app/controllers/buyer/plans_controller.rb
class Buyer::PlansController < ApplicationController
  def index
    @plans = Plan.all
  end

  def show
    @plan = Plan.find(params[:id])
  end
end

app/controllers/concerns/response.rb
module Response
  extend ActiveSupport::Concern

  def json_status(status, message)
    render json: {status: status, message: message}
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :root_redirect_path

  def index; end

  private

  def root_redirect_path
    redirect_to admin_plans_path if user_signed_in? && current_user.admin?
    redirect_to buyer_plans_path if user_signed_in? && current_user.buyer?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_bar
    return 'shared/navbar_admin' if current_user.admin?

    'shared/navbar_buyer'
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
  def get_consume_feature(consume_features, feature_id)
    consume_features.find { |consume_feature| consume_feature.feature_id == feature_id }
  end

  def due_payment(user)
    user.payments.where(payment: false).pluck(:total_bill).sum
  end
end

app/views/admin/usage/index.html.erb
<h1 class='text-center text-primary mt-2'>Subscribed Users</h1>
<div class='container'>
  <div class='row'>
    <% @users.each do |user| %>
      <div class='col-lg-4 col-sm-6 col-12'>
        <div class='card my-4'>
          <h5 class='card-header'>
            <div class='text-primary mb-2'>Username: </div> <%= user.name %>
          </h5>
          <div class='card-body'>
            <h5 class='card-title'>
              <div class='text-primary mb-2'>User Email: </div> <%= user.email %>
            </h5>
            <div class='d-flex flex-row'>
              <div class='btn-group mr-2 mt-4' role='group' aria-label='links'>
              <%= link_to 'View Subscribed Plans',  admin_usage_path(user), class:'btn btn-primary' %>
              </div>
              <div>
                <%= link_to 'View Payments',  admin_payment_path(user), class:'btn btn-primary ms-4 mt-4' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/usage/show.html.erb
<h1 class='text-center text-primary my-2'>Subscribed Plans</h1>
<% @subscriptions.each do |subscription| %>
  <ul class='list-group'>
    <li class='list-group-item'>
      <strong class='text-primary'>Subscription Name: </strong>
      <%= subscription.subscription_name %>
    </li>
    <li class='list-group-item'>
      <strong class='text-primary'>Monthly Fee: </strong> <%= subscription.price %>$
    </li>
    <% subscription.plan.features.each do |feature| %>
      <li class='list-group-item'>
        <strong class='text-primary'> Feature Name: </strong> <%= feature.feature_name %>
      </li>
      <li class='list-group-item'>
        <strong class='text-primary'> Unit Price: </strong> <%= feature.unit_price %>$
      </li>
      <li class='list-group-item'>
        <strong class='text-primary'> Max Unit Limit: </strong>
         <%= feature.max_unit_limit %>
      </li>
      <% consume_feature = get_consume_feature(subscription.consume_features, feature.id) %>
      <% if consume_feature %>
        <li class='list-group-item'>
          <strong class='text-primary'> Unit Cosnsumed: </strong>
          <%= consume_feature.consume_units %>
        </li>
      <% end %>
    <% end %>
  </ul>
  <li class='list-group-item my-2'>
     <%= link_to 'Generate Bill', admin_payments_path(payment: { user_id: @buyer.id, plan_id: subscription.plan.id}), method: :create, class: 'btn btn-success'%>
  </li>
  <hr class='border border-success border-3'>
<% end %>

<p class='text-center mt-2'>
  <strong class='text-success'>Due Bill is: </strong>
  <%= due_payment(@buyer) %>$</li>
</p>

app/views/welcome/index.html.erb
<h1 class='text-success my-2'>Welcome to Billing & Recurring Payment System</h1>
<h4>Please sign in to continue!</h4>