config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users, controllers: { invitations: 'users/invitations' }

  namespace :admin do
    resources :plans
    resources :features
    resources :usage
    resources :payments
  end   
  
  namespace :buyer do
    resources :plans, only: %i[index show]
    resources :subscriptions
    resources :consume_features do
      member do
        patch :increment_consumed_unit
      end
    end
    resources :payments do
      member do
        patch :payment_status
      end
    end
  end
  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'signup', to: 'registrations#create'
        post 'signin', to: 'sessions#create'
        delete 'signout', to: 'sessions#destroy'
      end
      resources :plans
      post 'my_plans', to: 'plans#my_plans'
      post 'subscribe', to: 'subscriptions#create'
      delete 'unsubscribe', to: 'subscriptions#destroy'
    end
  end
end

app/models/plan.rb
class Plan < ApplicationRecord
  validates :plan_name, :monthly_fee, presence: true

  has_many :feature_plans, dependent: :destroy
  has_many :features, through: :feature_plans
  accepts_nested_attributes_for :feature_plans, reject_if: :all_blank, allow_destroy: true
  has_many :subscriptions
  has_many :users, through: :subscriptions
  has_many :payments
end

app/controllers/admin/plans_controller.rb
class Admin::PlansController < Admin::AdminsController
  before_action :set_plan, only: %i[show edit update destroy]
  
  def index
    @plans = Plan.all
  end 
  
  def new
    @plan = Plan.new
  end  

  def create
    @plan = Plan.create(plan_params)

    if @plan.save 
      redirect_to admin_plans_path
    else
      render 'new'
    end   
  end

  def edit; end

  def update
    if @plan.update(plan_params)
      redirect_to admin_plans_path
    else
      render 'edit'
    end
  end

  def destroy
    @plan.destroy
    redirect_to admin_plans_path
  end

  private

  def plan_params
    params.require(:plan).permit(:plan_name, :monthly_fee, feature_plans_attributes: [:id, :plan_id, :feature_id, :allocated_units, :_destroy])
  end

  def set_plan
    @plan = Plan.find(params[:id])
  end
end 

app/controllers/api/v1/plans_controller.rb
class Api::V1::PlansController < Api::ApiController
  def index
     json_status(:ok, Plan.all)
  end

  def my_plans
    if current_user.subscriptions?
      json_status(:ok, current_user.subscriptions)
    else
      json_status(:not_found, 'User do not have any subscriptions')
  end
end

app/controllers/buyer/plans_controller.rb
class Buyer::PlansController < ApplicationController
  def index
    @plans = Plan.all
  end

  def show
    @plan = Plan.find(params[:id])
  end
end

app/views/admin/plans/_feature_plan_fields.html.erb
<div class='nested-fields'>
  <div class='my-2'>
    <%= f.collection_select( :feature_id, Feature.all, :id, :feature_name, {include_blank: false},
            multiple: false, class: 'select-feature') %>
  </div>
  <div class='my-2'>
    <%= link_to_remove_association 'Remove Feature', f, class: 'btn btn-danger' %>
  </div>
</div>

app/views/admin/plans/_form.html.erb
<%= simple_form_for [:admin, @plan] do |f| %>
  <%= f.input :plan_name %>
  <%= f.input :monthly_fee %>
  <div id='feature-plans'>
    <%= f.simple_fields_for :feature_plans do |feature| %>
      <%= render 'feature_plan_fields', f: :feature %>
    <% end %>
  </div>
  <div class="links">
    <%= link_to_add_association 'Add Feature', f, :feature_plans, class: 'btn btn-success my-2', form_name: 'f' %>
  </div>
  <%= f.button :submit, class: 'btn btn-default btn-primary my-4' %>
<% end %>

app/views/admin/plans/edit.html.erb
<h1>Edit Plan</h1>
<%= render 'form' %>
<%= link_to 'Back', admin_plans_path, class:'btn btn-lg btn-primary' %>

app/views/admin/plans/index.html.erb
<h1 class='text-center text-primary mt-2'>All Plans</h1>
<div class='container'>
  <div class='row'>
    <% @plans.each do |plan| %>
      <div class='col-lg-4 col-sm-6 col-12'>
        <div class='card my-4'>
        <h5 class='card-header'><%= plan.plan_name %></h5>
          <div class='card-body'>
          <h5 class='card-title'><%= plan.monthly_fee %>$</h5>
            <div class='btn-group mr-2 mt-4' role='group' aria-label='links'>
              <%= link_to 'Details', admin_plan_path(plan), class:'btn btn-primary' %>
              <%= link_to 'Edit', edit_admin_plan_path(plan), class:'btn btn-info' %>
              <%= link_to 'Destroy', admin_plan_path(plan), method: :delete,
                               class:'btn btn-danger', data: { confirm: 'Are you sure?'} %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/plans/new.html.erb
<h1>New Plan</h1>
<%= render 'form' %>
<%= link_to 'Back', admin_plans_path, class:'btn btn-primary' %>

app/views/admin/plans/show.html.erb
<div class='card my-2'>
  <div class='card-header text-primary'>
    <strong><%= @plan.plan_name %></strong>
  </div>
  <ul class='list-group list-group-flush'>
    <li class='list-group-item text-success'>
      <strong class='text-primary'>Price: </strong> <%= @plan.monthly_fee %>$
    </li>
    <li class='list-group-item'> <strong>Features:</strong> <%= render @plan.features %> </li>
    <li class='list-group-item'>
      <div class='btn-group mr-2' role='group' aria-label='links'>
        <%= link_to 'Edit', edit_admin_plan_path(@plan), class:'btn btn-primary' %>
        <%= link_to 'Back', admin_plans_path, class:'btn btn-info' %>
      </div>
    </li>
  </ul>
</div>